SELECT * FROM Sailors;
SELECT Sailors.A FROM Sailors;
SELECT S.A FROM Sailors S;
SELECT * FROM Sailors S WHERE S.A < 33;
SELECT * FROM Sailors, Reserves WHERE Sailors.A = Reserves.G;
SELECT * FROM Sailors S1, Sailors S2 WHERE S1.A < S2.A;
SELECT * FROM Sailors ORDER BY Sailors.B;
SELECT * FROM Boats B ORDER BY B.D;
SELECT DISTINCT R.G FROM Reserves R;
SELECT * FROM Boats, Sailors WHERE Boats.E = Sailors.A ORDER BY Boats.D;
SELECT DISTINCT R.G, S.A FROM Reserves R, Sailors S WHERE R.G < 13;
SELECT DISTINCT R.G, S.A FROM Reserves R, Sailors S WHERE R.G < 13 ORDER BY S.A;
SELECT Sailors.B, Sailors.C FROM Sailors ORDER BY Sailors.C;
SELECT * FROM Boats, Sailors;
SELECT R.G FROM Reserves R WHERE R.G > 48;
SELECT DISTINCT S.A, B.D, R.H FROM Sailors S, Boats B, Reserves R WHERE B.D > 22 AND S.A > 80 ORDER BY B.D, R.H; 
SELECT * FROM Sailors, Boats WHERE Boats.F = Sailors.A AND Sailors.C > Boats.D ORDER BY Boats.D;
SELECT Boats.D, Boats.F FROM Boats ORDER BY Boats.F;
SELECT DISTINCT S.B, S.C FROM Sailors S WHERE S.C > 88;
SELECT R.G FROM Reserves R WHERE R.G > 37;
SELECT * FROM Reserves R WHERE R.H > 22 ORDER BY R.H;
SELECT DISTINCT * FROM Sailors, Reserves, Boats WHERE Sailors.A > 90 AND Sailors.B > 85 ORDER BY Sailors.C, Reserves.G, Boats.E;
SELECT R.G, S.B, B.E FROM Reserves R, Sailors S, Boats B WHERE R.G > 48 AND B.E > 44 ORDER BY S.B;
SELECT DISTINCT Sailors.A, Boats.E FROM Sailors, Boats WHERE Sailors.A > Boats.E ORDER BY Boats.E;
SELECT S.C, B.F FROM Sailors S, Boats B WHERE S.C > B.D ORDER BY B.F;
SELECT S.C, B.F FROM Sailors S, Boats B WHERE S.C < B.D ORDER BY S.C, B.F;
SELECT * FROM Boats ORDER BY Boats.F, Boats.E, Boats.D;
SELECT * FROM Reserves ORDER BY Reserves.H;
SELECT * FROM Boats WHERE Boats.E = Boats.F;
SELECT * FROM Sailors, Boats WHERE Sailors.A = Boats.E AND Sailors.C < Boats.D ORDER BY Boats.E;
SELECT * FROM Sailors S1, Sailors S2 WHERE S1.B > S2.A AND S2.C < S1.B;
SELECT * FROM Boats B1, Boats B2, Sailors S WHERE B1.E = S.A AND S.B > B2.D ORDER BY B1.F;
SELECT * FROM Reserves R1, Reserves R2, Reserves R3 WHERE R1.G < R2.G AND R3.H > R2.H AND R3.H = 22 ORDER BY R1.H;
SELECT * FROM Reserves R1, Reserves R2 WHERE R1.H = R2.H AND R1.G > R2.G ORDER BY R2.G, R1.G;
SELECT * FROM Boats B1, Sailors S1, Sailors S2, Reserves R1 WHERE R1.H = B1.E AND B1.F < R1.G AND S1.C = S2.C AND S1.C < R1.H AND B1.E <= 37 AND S2.A != 69 AND S1.C = 33 ORDER BY R1.G, B1.D, S2.A;
SELECT * FROM Sailors, Reserves WHERE Sailors.A = 55;
SELECT S1.A, S2.B, B2.E, B3.F, R1.G FROM Sailors S1, Sailors S2, Boats B2, Boats B3, Reserves R1 WHERE S1.B > S2.C AND B2.E >= B3.D AND B3.D > S2.B AND S2.B > 22 AND B3.E = 33 AND R1.G = 9 AND R1.H = 11 AND S1.C > 90 ORDER BY S2.B, S1.A;